//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int NewsID { get; set; }
        public string NewsType { get; set; }
        public System.DateTime NewsDate { get; set; }
        public string ImgSrc { get; set; }
        public string ImgText { get; set; }
        public bool BigImg { get; set; }
    }
}
