//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public int ProfileID { get; set; }
        public string ProfileDescription { get; set; }
        public string BasicProfile { get; set; }
        public string Information { get; set; }
        public string Mutter { get; set; }
    }
}
